
import { LanguageKeys, TranslationKeys } from "@/types";

const translations: Record<LanguageKeys, Record<string, string>> = {
  english: {
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    home: "Home",
    search: "Search",
    loading: "Loading...",
    accept: "Accept",
    notifications: "Notifications",
    signup: "Sign Up",
    login: "Login",
    welcomeBack: "Welcome Back",
    forgotPassword: "Forgot Password?",
    username: "Username",
    password: "Password",
    lessons: "lessons",
    points: "points",
    learn: "Learn",
    games: "Games",
    community: "Community",
    profile: "Profile",
    reels: "Reels",
    saveMoney: "saved today",
    logout: "Logout",
    settings: "Settings",
    inbox: "Messages",
    badges: "My Badges",
    earnings: "My Earnings",
    progress: "Progress",
    complete: "Completed",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    correct: "You're right!",
    incorrect: "Try again!",
    congratulations: "Congratulations!",
    share: "Share",
    like: "Like",
    save: "Save",
    comment: "Comment",
    postComment: "Post Comment",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    report: "Report",
    helpText: "Need help? Ask me!",
    continueLesson: "Continue where you left off",
    tryNewGame: "Try this fun game!",
    dailyTip: "Today's Money Tip",
    viewAll: "View All",
    myProgress: "My Progress",
    myAchievements: "My Achievements",
    featuredContent: "Featured Today",
    learnMore: "Learn More",
    connectToFriends: "Connect with friends",
    inviteFriends: "Invite friends",
    addToYourSavings: "Add to your savings!",
    rate: "Rate this",
    feedback: "Give feedback",
    termsAccepted: "I accept the terms and conditions",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contactUs: "Contact Us",
    aboutUs: "About Us",
    help: "Help & FAQ",
    secureFinances: "Secure your finances",
    dailyCoins: "Daily Coins",
    framesLeft: "frames left",
    testYourSkills: "Test your skills",
    protectYourMoney: "Protect your money",
    scamAlert: "Is this a scam?",
    dailyChallenge: "Daily Challenge",
    responses: "Responses",
    start: "Start",
    results: "Results",
    seeDetails: "See Details",
    noResults: "No Results Found",
    noNotifications: "No notifications yet!",
    noMessages: "No messages yet",
    checkBackSoon: "Check back soon!",
    bringFriends: "Bring your friends",
    learnFromMasterji: "Learn from Masterji",
    quickQuiz: "Quick Quiz",
    nameCannotBeEmpty: "Name cannot be empty!",
    emailInvalid: "Invalid email address",
    wantToEarn: "Want to earn coins?",
    tips: "Tips & Tricks"
  },
  hindi: {
    firstName: "पहला नाम",
    lastName: "उपनाम",
    phoneNumber: "फोन नंबर",
    home: "होम",
    search: "खोजें",
    loading: "लोड हो रहा है...",
    accept: "स्वीकारें",
    notifications: "सूचनाएँ",
    signup: "साइन अप",
    login: "लॉग इन",
    welcomeBack: "वापसी पर स्वागत है",
    forgotPassword: "पासवर्ड भूल गए?",
    username: "यूजरनेम",
    password: "पासवर्ड",
    lessons: "पाठ",
    points: "अंक",
    learn: "सीखें",
    games: "खेल",
    community: "समुदाय",
    profile: "प्रोफाइल",
    reels: "रील्स",
    saveMoney: "आज बचाए",
    logout: "लॉग आउट",
    settings: "सेटिंग्स",
    inbox: "संदेश",
    badges: "मेरे बैज",
    earnings: "मेरी कमाई",
    progress: "प्रगति",
    complete: "पूर्ण",
    next: "अगला",
    previous: "पिछला",
    finish: "समाप्त",
    correct: "आप सही हैं!",
    incorrect: "फिर से कोशिश करें!",
    congratulations: "बधाई हो!",
    share: "शेयर",
    like: "लाइक",
    save: "सेव",
    comment: "कमेंट",
    postComment: "कमेंट करें",
    cancel: "रद्द करें",
    delete: "हटाएँ",
    edit: "संपादित करें",
    report: "रिपोर्ट",
    helpText: "मदद चाहिए? मुझसे पूछें!",
    continueLesson: "जहां छोड़ा था वहीं से जारी रखें",
    tryNewGame: "यह मजेदार गेम खेलें!",
    dailyTip: "आज का पैसा टिप",
    viewAll: "सभी देखें",
    myProgress: "मेरी प्रगति",
    myAchievements: "मेरी उपलब्धियां",
    featuredContent: "आज का विशेष",
    learnMore: "और जानें",
    connectToFriends: "दोस्तों से जुड़ें",
    inviteFriends: "दोस्तों को आमंत्रित करें",
    addToYourSavings: "अपनी बचत में जोड़ें!",
    rate: "रेटिंग दें",
    feedback: "फीडबैक दें",
    termsAccepted: "मैं नियम और शर्तों को स्वीकार करता हूँ",
    privacyPolicy: "प्राइवेसी पॉलिसी",
    termsOfService: "उपयोग की शर्तें",
    contactUs: "संपर्क करें",
    aboutUs: "हमारे बारे में",
    help: "मदद और सवाल",
    secureFinances: "अपने वित्त को सुरक्षित करें",
    dailyCoins: "दैनिक सिक्के",
    framesLeft: "फ्रेम बचे हैं",
    testYourSkills: "अपने कौशल का परीक्षण करें",
    protectYourMoney: "अपने पैसे की रक्षा करें",
    scamAlert: "क्या यह स्कैम है?",
    dailyChallenge: "दैनिक चुनौती",
    responses: "जवाब",
    start: "शुरू करें",
    results: "परिणाम",
    seeDetails: "विवरण देखें",
    noResults: "कोई परिणाम नहीं मिला",
    noNotifications: "अभी तक कोई सूचनाएँ नहीं!",
    noMessages: "अभी तक कोई संदेश नहीं",
    checkBackSoon: "जल्दी फिर आएं!",
    bringFriends: "अपने दोस्तों को लाओ",
    learnFromMasterji: "मास्टरजी से सीखें",
    quickQuiz: "क्विक क्विज़",
    nameCannotBeEmpty: "नाम खाली नहीं हो सकता!",
    emailInvalid: "अमान्य ईमेल पता",
    wantToEarn: "सिक्के कमाना चाहते हैं?",
    tips: "टिप्स और ट्रिक्स"
  },
  telugu: {
    firstName: "మొదటి పేరు",
    lastName: "ఇంటిపేరు",
    phoneNumber: "ఫోన్ నంబర్",
    home: "హోమ్",
    search: "వెతకండి",
    loading: "లోడ్ అవుతోంది...",
    accept: "అంగీకరించు",
    notifications: "నోటిఫికేషన్లు",
    signup: "సైన్ అప్",
    login: "లాగిన్",
    welcomeBack: "తిరిగి స్వాగతం",
    forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
    username: "యూజర్నేమ్",
    password: "పాస్వర్డ్",
    lessons: "పాఠాలు",
    points: "పాయింట్లు",
    learn: "నేర్చుకోండి",
    games: "ఆటలు",
    community: "సమూహం",
    profile: "ప్రొఫైల్",
    reels: "రీల్స్",
    saveMoney: "ఈరోజు ఆదా చేశారు",
    logout: "లాగౌట్",
    settings: "సెట్టింగ్స్",
    inbox: "సందేశాలు",
    badges: "నా బ్యాడ్జ్‌లు",
    earnings: "నా ఆదాయాలు",
    progress: "పురోగతి",
    complete: "పూర్తి",
    next: "తదుపరి",
    previous: "మునుపటి",
    finish: "ముగింపు",
    correct: "మీరు సరైనది చెప్పారు!",
    incorrect: "మళ్లీ ప్రయత్నించండి!",
    congratulations: "అభినందనలు!",
    share: "షేర్",
    like: "లైక్",
    save: "సేవ్",
    comment: "కామెంట్",
    postComment: "కామెంట్ పోస్ట్ చేయి",
    cancel: "రద్దు",
    delete: "తొలగించు",
    edit: "సవరించు",
    report: "రిపోర్ట్",
    helpText: "సహాయం కావాలా? నన్ను అడగండి!",
    continueLesson: "మీరు విడిచిపెట్టిన చోట కొనసాగించండి",
    tryNewGame: "ఈ ఆట ఆడండి!",
    dailyTip: "ఈరోజు డబ్బు చిట్కా",
    viewAll: "అన్నీ చూడు",
    myProgress: "నా పురోగతి",
    myAchievements: "నా సాధనలు",
    featuredContent: "నేటి హైలైట్",
    learnMore: "మరింత తెలుసుకోండి",
    connectToFriends: "స్నేహితులతో కలవండి",
    inviteFriends: "స్నేహితులను ఆహ్వానించండి",
    addToYourSavings: "మీ పొదుపులో చేర్చండి!",
    rate: "రేటింగ్ ఇవ్వండి",
    feedback: "అభిప్రాయం తెలపండి",
    termsAccepted: "నేను నిబంధనలు మరియు షరతులను అంగీకరిస్తున్నాను",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    aboutUs: "మా గురించి",
    help: "సహాయం & తరచుగా అడిగే ప్రశ్నలు",
    secureFinances: "మీ ఆర్థిక వ్యవహారాలను సురక్షితం చేయండి",
    dailyCoins: "రోజువారీ నాణేలు",
    framesLeft: "ఫ్రేమ్లు మిగిలి ఉన్నాయి",
    testYourSkills: "మీ నైపుణ్యాలను పరీక్షించండి",
    protectYourMoney: "మీ డబ్బును రక్షించుకోండి",
    scamAlert: "ఇది మోసమా?",
    dailyChallenge: "రోజువారీ ఛాలెంజ్",
    responses: "సమాధానాలు",
    start: "ప్రారంభించు",
    results: "ఫలితాలు",
    seeDetails: "వివరాలు చూడండి",
    noResults: "ఫలితాలు కనుగొనబడలేదు",
    noNotifications: "ఇంకా నోటిఫికేషన్లు లేవు!",
    noMessages: "ఇంకా సందేశాలు లేవు",
    checkBackSoon: "త్వరలో మళ్ళీ చూడండి!",
    bringFriends: "మీ స్నేహితులను తీసుకురండి",
    learnFromMasterji: "మాష్టారి నుండి నేర్చుకోండి",
    quickQuiz: "త్వరిత క్విజ్",
    nameCannotBeEmpty: "పేరు ఖాళీగా ఉండకూడదు!",
    emailInvalid: "చెల్లని ఇమెయిల్ చిరునామా",
    wantToEarn: "నాణేలు సంపాదించాలనుకుంటున్నారా?",
    tips: "చిట్కాలు & ట్రిక్స్"
  }
};

export const translate = (key: string, language: LanguageKeys): string => {
  // Check if key exists in translations
  if (!translations[language][key as keyof typeof translations[typeof language]]) {
    console.warn(`Translation key "${key}" not found for language "${language}"`);
    return key;
  }
  
  return translations[language][key as keyof typeof translations[typeof language]];
};

export const getRandomGreeting = (language: LanguageKeys) => {
  const greetings = {
    english: [
      "Hey there!",
      "Welcome back!",
      "Good to see you!",
      "Howdy, partner!",
      "Hello, friend!"
    ],
    hindi: [
      "नमस्ते दोस्त!",
      "कैसे हो आप?",
      "आपका स्वागत है!",
      "शुभ दिन!",
      "अरे वाह!"
    ],
    telugu: [
      "నమస్కారం!",
      "బాగున్నారా?",
      "స్వాగతం!",
      "శుభోదయం!",
      "మంచి రోజు!"
    ]
  };
  
  const randomIndex = Math.floor(Math.random() * greetings[language].length);
  return greetings[language][randomIndex];
};

export const getMotivationalPhrase = (category: string, language: LanguageKeys) => {
  const phrases = {
    english: {
      savings: "Small savings today, big dreams tomorrow!",
      investment: "Start small, grow big!",
      fraud: "Stay alert, stay secure!",
      borrowing: "Borrow wisely!",
      basics: "First step is the most important!",
      default: "Knowledge is power!"
    },
    hindi: {
      savings: "छोटी बचत, बड़े सपने!",
      investment: "छोटा निवेश, बड़ी कमाई!",
      fraud: "सावधान रहें, सुरक्षित रहें!",
      borrowing: "समझदारी से लें कर्ज़!",
      basics: "पहला कदम सबसे महत्वपूर्ण है!",
      default: "ज्ञान ही शक्ति है!"
    },
    telugu: {
      savings: "చిన్న పొదుపులు, పెద్ద కలలు!",
      investment: "చిన్నగా మొదలు, పెద్దగా పెరుగు!",
      fraud: "అప్రమత్తంగా ఉండండి, సురక్షితంగా ఉండండి!",
      borrowing: "తెలివిగా అప్పు తీసుకోండి!",
      basics: "మొదటి అడుగు చాలా ముఖ్యం!",
      default: "జ్ఞానమే శక్తి!"
    }
  };
  
  return phrases[language][category as keyof typeof phrases[typeof language]] || phrases[language].default;
};
