
import { LanguageKeys } from "../types";

export const LANGUAGES = {
  ENGLISH: 'english',
  HINDI: 'hindi',
  TELUGU: 'telugu'
} as const;

export const DEFAULT_LANGUAGE: LanguageKeys = 'english';

export const LANGUAGE_DETAILS = [
  { value: 'english', label: 'English', flag: '🇬🇧' },
  { value: 'hindi', label: 'हिंदी', flag: '🇮🇳' },
  { value: 'telugu', label: 'తెలుగు', flag: '🇮🇳' },
] as const;

const translations = {
  english: {
    signup: "Sign Up",
    login: "Log In",
    welcomeBack: "Welcome Back",
    forgotPassword: "Forgot Password",
    username: "Phone Number",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    termsAccepted: "I accept the terms and conditions",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    loginText: "Log in",
    orSignUpWith: "Or sign up with",
    loading: "Loading...",
    freeAccess: "14-day free access to unlimited resources",
    welcomeTitle: "Join the CoinWise Family!",
    welcomeMessage: "Start your financial journey today",
    phoneNumber: "Phone Number",
    home: "Home",
    reels: "Reels",
    games: "Games",
    learn: "Learn",
    community: "Community",
    profile: "Profile",
    notifications: "Notifications",
    search: "Search",
    settings: "Settings",
    continue: "Continue",
    next: "Next",
    back: "Back",
    done: "Done",
    skip: "Skip",
    cancel: "Cancel",
    accept: "Accept",
    decline: "Decline",
    complete: "Complete",
    congratulations: "Congratulations",
    startLearning: "Start Learning",
    startGame: "Start Game",
    myProgress: "My Progress",
    myBadges: "My Badges",
    myAchievements: "My Achievements",
    saveMoney: "Save Money",
    investWisely: "Invest Wisely",
    avoidScams: "Avoid Scams",
    learnBudgeting: "Learn Budgeting",
    secureFinances: "Secure Finances"
  },
  hindi: {
    signup: "साइन अप करें",
    login: "लॉग इन",
    welcomeBack: "वापसी पर स्वागत है",
    forgotPassword: "पासवर्ड भूल गए",
    username: "फोन नंबर",
    password: "पासवर्ड",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    termsAccepted: "मैं नियम और शर्तों को स्वीकार करता हूं",
    createAccount: "खाता बनाएँ",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    loginText: "लॉग इन करें",
    orSignUpWith: "या इसके साथ साइन अप करें",
    loading: "लोड हो रहा है...",
    freeAccess: "असीमित संसाधनों तक 14-दिन का मुफ्त एक्सेस",
    welcomeTitle: "CoinWise परिवार में आपका स्वागत है!",
    welcomeMessage: "आज ही अपनी वित्तीय यात्रा शुरू करें",
    phoneNumber: "फोन नंबर",
    home: "होम",
    reels: "रील्स",
    games: "गेम्स",
    learn: "सीखें",
    community: "समुदाय",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
    search: "खोज",
    settings: "सेटिंग्स",
    continue: "जारी रखें",
    next: "अगला",
    back: "वापस",
    done: "हो गया",
    skip: "छोड़ें",
    cancel: "रद्द करें",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    complete: "पूर्ण",
    congratulations: "बधाई हो",
    startLearning: "सीखना शुरू करें",
    startGame: "खेल शुरू करें",
    myProgress: "मेरी प्रगति",
    myBadges: "मेरे बैज",
    myAchievements: "मेरी उपलब्धियां",
    saveMoney: "पैसे बचाएं",
    investWisely: "बुद्धिमानी से निवेश करें",
    avoidScams: "घोटालों से बचें",
    learnBudgeting: "बजट बनाना सीखें",
    secureFinances: "वित्त सुरक्षित करें"
  },
  telugu: {
    signup: "సైన్ అప్",
    login: "లాగిన్",
    welcomeBack: "తిరిగి వచ్చినందుకు స్వాగతం",
    forgotPassword: "పాస్వర్డ్ మర్చిపోయాను",
    username: "ఫోన్ నంబర్",
    password: "పాస్‌వర్డ్",
    firstName: "మొదటి పేరు",
    lastName: "చివరి పేరు",
    termsAccepted: "నేను నిబంధనలు మరియు షరతులను అంగీకరిస్తున్నాను",
    createAccount: "ఖాతా సృష్టించండి",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    loginText: "లాగిన్ చేయండి",
    orSignUpWith: "లేదా దీనితో సైన్ అప్ చేయండి",
    loading: "లోడ్ అవుతోంది...",
    freeAccess: "అపరిమిత వనరులకు 14 రోజుల ఉచిత యాక్సెస్",
    welcomeTitle: "CoinWise కుటుంబంలోకి స్వాగతం!",
    welcomeMessage: "మీ ఆర్థిక ప్రయాణాన్ని ఇప్పుడే ప్రారంభించండి",
    phoneNumber: "ఫోన్ నంబర్",
    home: "హోమ్",
    reels: "రీల్స్",
    games: "గేమ్స్",
    learn: "నేర్చుకోండి",
    community: "సమాజం",
    profile: "ప్రొఫైల్",
    notifications: "నోటిఫికేషన్స్",
    search: "శోధన",
    settings: "సెట్టింగులు",
    continue: "కొనసాగించండి",
    next: "తదుపరి",
    back: "వెనుకకు",
    done: "పూర్తయింది",
    skip: "దాటవేయండి",
    cancel: "రద్దు చేయండి",
    accept: "అంగీకరించండి",
    decline: "తిరస్కరించండి",
    complete: "పూర్తి",
    congratulations: "అభినందనలు",
    startLearning: "నేర్చుకోవడం ప్రారంభించండి",
    startGame: "ఆట ప్రారంభించండి",
    myProgress: "నా పురోగతి",
    myBadges: "నా బ్యాడ్జీలు",
    myAchievements: "నా విజయాలు",
    saveMoney: "డబ్బు ఆదా చేయండి",
    investWisely: "తెలివిగా పెట్టుబడి పెట్టండి",
    avoidScams: "మోసాలను నివారించండి",
    learnBudgeting: "బడ్జెట్ చేయడం నేర్చుకోండి",
    secureFinances: "ఆర్థిక భద్రత"
  }
};

export const translate = (key: keyof typeof translations.english, language: LanguageKeys = DEFAULT_LANGUAGE): string => {
  return translations[language][key] || translations.english[key] || key;
};
